name: Server

on:
  workflow_run:
    workflows: ["server"]
    types:
      - completed
    # Restart job if it fails
    result: failure

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start server
        run: |
          nohup ./start-server.sh &
          while true; do
            # Keep job running
            sleep 10
          done
