name: Start Server

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start server
        env:
          START_SCRIPT: ${{ secrets.START_SERVER_SCRIPT }}
        run: |
          nohup ${START_SCRIPT} &
          sleep infinity
